### ISSUE TITLE
Create option for R1_PrepareRecData.py to parse a  list of z values to the script

### ISSUE THREAD

**Issue by FilipsFedotovs** [FilipsFedotovs/EDER-VIANN#53]
The final goal is to be able to parse a list of values of  z values to R1_PrepareRecData.py for example:
python3 R1_PrepareRecData.py --RemoveTracksZ [12000, 13000]

Acceptance criteria: By parsing this option in this script we enable it to have a list variable inside of the script with parsed values.

First of all:
1) Go to your lxplus directory
2) Create folder for your new script (the branch that we have created earlier)
3)  git clone https://github.com/FilipsFedotovs/EDER-VIANN --branch leahhwolf-snd
4)  Go to setup directory and run setup.py
5) Once it is done, go back to your local directory on your PC and open R1_PrepareRecData.py in the editor of your choice.
6) Place exit() after line 25
7) Now here is where you need to use google or other code in the same project to add parser and be able to supply command with list inputs. You can add the parser line with name --RemoveTracksZ next to other parser lines that are already there between lines 18 and 23.
8) Once you add parser you need to create a variable called RemoveTracksZ that takes input from the parser and converts it to list.
9) Test that the variable works correctly by using print(RemoveTracksZ) function,
10) All lines of code have to be added before exit() line that we have added earlier.
11) Once changes have been implemented you can test it by uploading the changed file to Github to your branch.
12) Once you have committed go back to lxplus location (step 4) and run 'git pull' command.
13) Run the command by using python3 R1_PrepareRecData.py --RemoveTracksZ [12000, 13000]. Most likely there will be an error. Change the file on the local machine accordingly and commit to the GitHub->git pull on lxplus -> python3 R1_PrepareRecData.py --RemoveTracksZ [12000, 13000]
14) Repeat until successful (you should get the correct printout result: [12000, 13000] on the screen.

**Comment by leahhwolf** [comment]
Hi Filips, in the setup what should I put when it asks for the full path of the directory on EOS? Each one I've tried comes back saying 'Disc quota exceeded'

**Comment by FilipsFedotovs** [comment]
I think this is because your space on local drive is maxed out. 
There are two ways to deal with it:
1) Clean your AFS directory
2) Increase size of AFS working directory (You can get extra quota on cern account settings).

What is the full pass to directory on AFS where are your trying to install EDER-GNN?
